apiVersion: v2
name: forge-c2
description: FORGE-C2 Military C2 Simulation Platform
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - c2
  - simulation
  - dis
  - hla
  - link16
  - tena
maintainers:
  - name: STSGYM
    email: wlrobbi@stsgym.com
