apiVersion: v1
kind: Secret
metadata:
  name: forge-c2-secret
  namespace: gms
type: Opaque
stringData:
  KAFKA_USERNAME: "forge-c2"
  KAFKA_PASSWORD: "CHANGE-ME"
  C2BMC_TOKEN: "CHANGE-ME"
  JREAP_AUTH_TOKEN: "CHANGE-ME"