apiVersion: v1
kind: ConfigMap
metadata:
  name: forge-c2-config
  namespace: gms
data:
  FORGE_C2_PORT: "8080"
  KAFKA_BROKER: "kafka.gms.svc.cluster.local:9092"
  C2BMC_URL: "http://c2bmc.gms.svc.cluster.local:5016"
  JREAP_UDP_PORT: "5000"
  JREAP_TCP_PORT: "5001"
  DIS_PORT: "3000"
  LOG_LEVEL: "info"