import { IanDisplays } from '../../../src/ts/displays/types';
import { convertToEntityReference } from '../../../src/ts/faceted';
import type {
  DisplayLayouts,
  GlobalPreferences,
  MapDisplaySettings,
  StationVisibilityList,
  UiUserPreferences,
  UserPreferencesKeyboardShortcuts,
  UserProfile,
  WaveformDisplayLayout,
  WorkspaceLayout
} from '../../../src/ts/user-profile';
import { asar, pdar } from '../station-definitions';

export const globalPreferencesData: GlobalPreferences = {
  colorMap: 'turbo',
  currentTheme: 'GMS Dark Theme',
  hideEmptyWaveformRows: 'PER_MODE',
  numberVisibleWaveformsOption: 'PER_MODE',
  customNumberVisibleWaveforms: 10
};

export const mapDisplaySettingsData: MapDisplaySettings = {
  twoDimensional: true,
  layerVisibility: {
    regions: true,
    flinnEngdahlGeographic: true,
    flinnEngdahlSeismic: true,
    ocean: true,
    land: true,
    eventNotification1: true,
    eventNotification2: true,
    stations: true,
    sites: false,
    eventsDeleted: true,
    eventsRejected: true,
    preferredLocationSolution: true,
    edgeEventsBeforeInterval: true,
    edgeEventsAfterInterval: true,
    nonPreferredLocationSolution: false,
    confidenceEllipse: true,
    coverageEllipse: true,
    edgeDetectionBefore: true,
    edgeDetectionAfter: true,
    unassociatedDetection: true,
    associatedOpenDetection: true,
    associatedOtherDetection: true,
    associatedCompleteDetection: true,
    deletedDetection: true
  },
  syncToWaveformDisplayVisibleTimeRange: false
};

export const workspaceLayoutsData: WorkspaceLayout[] = [
  {
    name: 'Analyst Displays Layout',
    layoutConfiguration:
      '%7B%22settings%22:%7B%22hasHeaders%22:true,%22constrainDragToContainer%22:true,%22reorderEnabled%22:true,%22selectionEnabled%22:false,%22popoutWholeStack%22:false,%22blockedPopoutsThrowError%22:true,%22closePopoutsOnUnload%22:true,%22showPopoutIcon%22:false,%22showMaximiseIcon%22:true,%22showCloseIcon%22:true,%22responsiveMode%22:%22onload%22,%22tabOverlapAllowance%22:0,%22reorderOnTabMenuClick%22:true,%22tabControlOffset%22:10%7D,%22dimensions%22:%7B%22borderWidth%22:2,%22borderGrabWidth%22:15,%22minItemHeight%22:30,%22minItemWidth%22:30,%22headerHeight%22:30,%22dragProxyWidth%22:300,%22dragProxyHeight%22:200%7D,%22labels%22:%7B%22close%22:%22close%22,%22maximise%22:%22maximise%22,%22minimise%22:%22minimise%22,%22popout%22:%22open%20in%20new%20window%22,%22popin%22:%22pop%20in%22,%22tabDropdown%22:%22additional%20tabs%22%7D,%22content%22:%5B%7B%22type%22:%22row%22,%22isClosable%22:true,%22reorderEnabled%22:true,%22title%22:%22%22,%22content%22:%5B%7B%22type%22:%22stack%22,%22isClosable%22:true,%22reorderEnabled%22:true,%22title%22:%22%22,%22activeItemIndex%22:0,%22width%22:50,%22content%22:%5B%7B%22type%22:%22component%22,%22title%22:%22Waveforms%22,%22component%22:%22waveform-display%22,%22componentName%22:%22lm-react-component%22,%22isClosable%22:true,%22reorderEnabled%22:true%7D%5D%7D,%7B%22type%22:%22column%22,%22isClosable%22:true,%22reorderEnabled%22:true,%22title%22:%22%22,%22width%22:50,%22content%22:%5B%7B%22type%22:%22stack%22,%22header%22:%7B%7D,%22isClosable%22:true,%22reorderEnabled%22:true,%22title%22:%22%22,%22activeItemIndex%22:0,%22height%22:43.388429752066116,%22content%22:%5B%7B%22type%22:%22component%22,%22title%22:%22Station%20Properties%22,%22component%22:%22station-properties%22,%22componentName%22:%22lm-react-component%22,%22isClosable%22:true,%22reorderEnabled%22:true%7D%5D%7D,%7B%22type%22:%22stack%22,%22header%22:%7B%7D,%22isClosable%22:true,%22reorderEnabled%22:true,%22title%22:%22%22,%22activeItemIndex%22:0,%22width%22:50,%22height%22:56.611570247933884,%22content%22:%5B%7B%22type%22:%22component%22,%22title%22:%22Map%22,%22component%22:%22map-display%22,%22componentName%22:%22lm-react-component%22,%22isClosable%22:true,%22reorderEnabled%22:true%7D%5D%7D%5D%7D%5D%7D%5D,%22isClosable%22:true,%22reorderEnabled%22:true,%22title%22:%22%22,%22openPopouts%22:%5B%5D,%22maximisedItemId%22:null%7D'
  }
];

export const displayLayoutsData: DisplayLayouts = {
  [IanDisplays.AZIMUTH_SLOWNESS]: {
    columnOrder: ['description', 'peak', 'predicted', 'measured', 'residual'],
    thumbnailSize: 120,
    thumbnailColumnWidth: 302,
    fkStepsVisible: false,
    fkPreviewsVisible: false,
    fkBeamsAndTracesVisible: true
  },
  [IanDisplays.EVENTS]: {
    columnVisibility: {
      unsavedChanges: true,
      conflict: true,
      time: true,
      timeUncertainty: true,
      latitudeDegrees: true,
      longitudeDegrees: true,
      depthKm: true,
      depthUncertainty: true,
      magnitudeMb: true,
      magnitudeMs: true,
      magnitudeMl: true,
      numberAssociated: true,
      numberDefining: true,
      observationsStandardDeviation: true,
      coverageSemiMajorAxis: true,
      coverageSemiMinorAxis: true,
      coverageSemiMajorTrend: true,
      coverageAreaOfEllipse: true,
      confidenceSemiMajorAxis: true,
      confidenceSemiMinorAxis: true,
      confidenceSemiMajorTrend: true,
      confidenceAreaOfEllipse: true,
      kWeight: true,
      kWeightedSemiMajorAxisLengthKm: true,
      kWeightedSemiMinorAxisLengthKm: true,
      kWeightedSemiMajorAxisTrendDeg: true,
      kWeightedAreaOfEllipse: true,
      region: true,
      activeAnalysts: true,
      preferred: true,
      status: true,
      rejected: true,
      deleted: true
    },
    pinnedColumns: {},
    columnOrder: [
      'unsavedChanges',
      'conflict',
      'time',
      'timeUncertainty',
      'latitudeDegrees',
      'longitudeDegrees',
      'depthKm',
      'depthUncertainty',
      'magnitudeMb',
      'magnitudeMs',
      'magnitudeMl',
      'numberAssociated',
      'numberDefining',
      'observationsStandardDeviation',
      'coverageSemiMajorAxis',
      'coverageSemiMinorAxis',
      'coverageSemiMajorTrend',
      'coverageAreaOfEllipse',
      'confidenceSemiMajorAxis',
      'confidenceSemiMinorAxis',
      'confidenceSemiMajorTrend',
      'confidenceAreaOfEllipse',
      'kWeight',
      'kWeightedSemiMajorAxisLengthKm',
      'kWeightedSemiMinorAxisLengthKm',
      'kWeightedSemiMajorAxisTrendDeg',
      'kWeightedAreaOfEllipse',
      'region',
      'activeAnalysts',
      'preferred',
      'status',
      'rejected',
      'deleted'
    ],
    columnWidths: {
      unsavedChanges: 60,
      conflict: 60,
      time: 300,
      timeUncertainty: 150,
      latitudeDegrees: 105,
      longitudeDegrees: 105,
      depthKm: 200,
      depthUncertainty: 150,
      magnitudeMb: 60,
      magnitudeMs: 60,
      magnitudeMl: 60,
      numberAssociated: 140,
      numberDefining: 125,
      observationsStandardDeviation: 105,
      coverageSemiMajorAxis: 260,
      coverageSemiMinorAxis: 260,
      coverageSemiMajorTrend: 290,
      coverageAreaOfEllipse: 300,
      confidenceSemiMajorAxis: 270,
      confidenceSemiMinorAxis: 270,
      confidenceSemiMajorTrend: 310,
      confidenceAreaOfEllipse: 315,
      kWeight: 185,
      kWeightedSemiMajorAxisLengthKm: 230,
      kWeightedSemiMinorAxisLengthKm: 230,
      kWeightedSemiMajorAxisTrendDeg: 280,
      kWeightedAreaOfEllipse: 320,
      region: 105,
      activeAnalysts: 200,
      preferred: 115,
      status: 110,
      rejected: 110,
      deleted: 105
    },
    visibleEvents: {
      edgeEventsBeforeInterval: true,
      edgeEventsAfterInterval: true,
      eventsCompleted: true,
      eventsRemaining: true,
      eventsConflict: true,
      eventsDeleted: true,
      eventsRejected: true
    }
  },
  [IanDisplays.SIGNAL_DETECTIONS]: {
    columnVisibility: {
      unsavedChanges: true,
      assocStatus: true,
      conflict: true,
      station: true,
      channel: true,
      phase: true,
      phaseConfidence: false,
      time: true,
      timeUncertainty: true,
      azimuth: true,
      azimuthStandardDeviation: true,
      slowness: true,
      slownessStandardDeviation: true,
      amplitude: true,
      period: true,
      amplitudeType: true,
      sNR: true,
      rectilinearity: false,
      emergenceAngle: false,
      shortPeriodFirstMotion: false,
      longPeriodFirstMotion: false,
      deleted: true
    },
    pinnedColumns: {},
    columnOrder: [
      'unsavedChanges',
      'assocStatus',
      'conflict',
      'station',
      'channel',
      'phase',
      'phaseConfidence',
      'time',
      'timeUncertainty',
      'azimuth',
      'azimuthStandardDeviation',
      'slowness',
      'slownessStandardDeviation',
      'amplitude',
      'period',
      'amplitudeType',
      'sNR',
      'rectilinearity',
      'emergenceAngle',
      'shortPeriodFirstMotion',
      'longPeriodFirstMotion',
      'deleted'
    ],
    columnWidths: {
      unsavedChanges: 60,
      assocStatus: 83,
      conflict: 60,
      station: 105,
      channel: 200,
      phase: 105,
      phaseConfidence: 105,
      time: 300,
      timeUncertainty: 150,
      azimuth: 150,
      azimuthStandardDeviation: 165,
      slowness: 150,
      slownessStandardDeviation: 165,
      amplitude: 130,
      period: 105,
      amplitudeType: 105,
      sNR: 105,
      rectilinearity: 105,
      emergenceAngle: 105,
      shortPeriodFirstMotion: 200,
      longPeriodFirstMotion: 200,
      deleted: 105
    },
    visibleSignalDetections: {
      syncWaveform: false,
      signalDetectionBeforeInterval: true,
      signalDetectionAfterInterval: true,
      signalDetectionAssociatedToOpenEvent: true,
      signalDetectionAssociatedToCompletedEvent: true,
      signalDetectionAssociatedToOtherEvent: true,
      signalDetectionConflicts: true,
      signalDetectionDeleted: true,
      signalDetectionUnassociated: true
    }
  },
  [IanDisplays.LOCATION]: {
    displayOne: {
      columnVisibility: {
        savePoint: true,
        preferred: true,
        time: true,
        timeUncertainty: true,
        latitudeDegrees: true,
        longitudeDegrees: true,
        depthKm: true,
        depthUncertainty: true,
        restraint: true,
        stdDevTravelTimeResiduals: true,
        numberOfAssociated: true,
        numberOfDefining: true,
        region: true,
        coverageSemiMajorAxisLengthKm: true,
        coverageSemiMinorAxisLengthKm: true,
        coverageSemiMajorAxisTrendDeg: true,
        coverageAreaOfEllipse: true,
        confidenceSemiMajorAxisLengthKm: true,
        confidenceSemiMinorAxisLengthKm: true,
        confidenceSemiMajorAxisTrendDeg: true,
        confidenceAreaOfEllipse: true,
        kWeight: true,
        kWeightedSemiMajorAxisLengthKm: true,
        kWeightedSemiMinorAxisLengthKm: true,
        kWeightedSemiMajorAxisTrendDeg: true,
        kWeightedAreaOfEllipse: true
      },
      pinnedColumns: {},
      columnOrder: [
        'savePoint',
        'preferred',
        'time',
        'timeUncertainty',
        'latitudeDegrees',
        'longitudeDegrees',
        'depthKm',
        'depthUncertainty',
        'restraint',
        'stdDevTravelTimeResiduals',
        'numberOfAssociated',
        'numberOfDefining',
        'region',
        'coverageSemiMajorAxisLengthKm',
        'coverageSemiMinorAxisLengthKm',
        'coverageSemiMajorAxisTrendDeg',
        'coverageAreaOfEllipse',
        'confidenceSemiMajorAxisLengthKm',
        'confidenceSemiMinorAxisLengthKm',
        'confidenceSemiMajorAxisTrendDeg',
        'confidenceAreaOfEllipse',
        'kWeight',
        'kWeightedSemiMajorAxisLengthKm',
        'kWeightedSemiMinorAxisLengthKm',
        'kWeightedSemiMajorAxisTrendDeg',
        'kWeightedAreaOfEllipse'
      ],
      columnWidths: {
        savePoint: 40,
        preferred: 105,
        time: 300,
        timeUncertainty: 150,
        latitudeDegrees: 105,
        longitudeDegrees: 105,
        depthKm: 200,
        depthUncertainty: 150,
        restraint: 150,
        stdDevTravelTimeResiduals: 105,
        numberOfAssociated: 140,
        numberOfDefining: 125,
        region: 90,
        coverageSemiMajorAxisLengthKm: 240,
        coverageSemiMinorAxisLengthKm: 240,
        coverageSemiMajorAxisTrendDeg: 280,
        coverageAreaOfEllipse: 285,
        confidenceSemiMajorAxisLengthKm: 260,
        confidenceSemiMinorAxisLengthKm: 260,
        confidenceSemiMajorAxisTrendDeg: 300,
        confidenceAreaOfEllipse: 305,
        kWeight: 170,
        kWeightedSemiMajorAxisLengthKm: 215,
        kWeightedSemiMinorAxisLengthKm: 215,
        kWeightedSemiMajorAxisTrendDeg: 265,
        kWeightedAreaOfEllipse: 305
      }
    },
    displayTwo: {
      columnVisibility: {
        conflict: true,
        isAddedSignalDetection: true,
        isDeletedSignalDetection: true,
        station: true,
        channel: true,
        phase: true,
        distance: true,
        az: true,
        arrivalTimeObserved: true,
        arrivalTimeStdDev: true,
        arrivalTimeResidual: true,
        arrivalTimeUsed: true,
        arrivalTimeDefining: true,
        azimuthObserved: true,
        azimuthStdDev: true,
        azimuthResidual: true,
        azimuthUsed: true,
        azimuthDefining: true,
        slownessObserved: true,
        slownessStdDev: true,
        slownessResidual: true,
        slownessUsed: true,
        slownessDefining: true
      },
      columnOrder: [
        'conflict',
        'isAddedSignalDetection',
        'isDeletedSignalDetection',
        'station',
        'channel',
        'phase',
        'distance',
        'az',
        'arrivalTimeObserved',
        'arrivalTimeStdDev',
        'arrivalTimeResidual',
        'arrivalTimeUsed',
        'arrivalTimeDefining',
        'azimuthObserved',
        'azimuthStdDev',
        'azimuthResidual',
        'azimuthUsed',
        'azimuthDefining',
        'slownessObserved',
        'slownessStdDev',
        'slownessResidual',
        'slownessUsed',
        'slownessDefining'
      ],
      columnWidths: {
        conflict: 60,
        isAddedSignalDetection: 60,
        isDeletedSignalDetection: 60,
        station: 100,
        channel: 100,
        phase: 100,
        distance: 100,
        az: 100,
        arrivalTimeObserved: 280,
        arrivalTimeStdDev: 125,
        arrivalTimeResidual: 130,
        arrivalTimeUsed: 100,
        arrivalTimeDefining: 62,
        azimuthObserved: 130,
        azimuthStdDev: 125,
        azimuthResidual: 130,
        azimuthUsed: 100,
        azimuthDefining: 62,
        slownessObserved: 130,
        slownessStdDev: 125,
        slownessResidual: 130,
        slownessUsed: 100,
        slownessDefining: 62
      }
    }
  },
  [IanDisplays.STATION_PROPERTIES]: {
    displayOne: {
      columnVisibility: {
        name: true,
        effectiveAt: true,
        effectiveUntil: true,
        latitudeDegrees: true,
        longitudeDegrees: true,
        depthKm: true,
        elevationKm: true,
        type: true,
        description: true
      },
      pinnedColumns: {},
      columnOrder: [
        'name',
        'effectiveAt',
        'effectiveUntil',
        'latitudeDegrees',
        'longitudeDegrees',
        'depthKm',
        'elevationKm',
        'type',
        'description'
      ],
      columnWidths: {
        name: 200,
        effectiveAt: 200,
        effectiveUntil: 200,
        latitudeDegrees: 105,
        longitudeDegrees: 105,
        depthKm: 105,
        elevationKm: 105,
        type: 200,
        description: 300
      }
    },
    displayTwo: {
      columnVisibility: {
        name: true,
        effectiveAt: true,
        effectiveUntil: true,
        latitudeDegrees: true,
        longitudeDegrees: true,
        depthKm: true,
        elevationKm: true,
        nominalSampleRateHz: true,
        units: true,
        orientationHorizontalDegrees: true,
        orientationVerticalDegrees: true,
        calibrationFactor: true,
        calibrationPeriod: true,
        calibrationEffectiveAt: true,
        calibrationTimeShift: true,
        calibrationStandardDeviation: true,
        northDisplacementKm: true,
        eastDisplacementKm: true,
        verticalDisplacementKm: true,
        description: true,
        channelDataType: false,
        channelBandType: false,
        channelInstrumentType: false,
        channelOrientationCode: false,
        channelOrientationType: false,
        calibrationResponseId: true,
        fapResponseId: true
      },
      pinnedColumns: {},
      columnOrder: [
        'name',
        'effectiveAt',
        'effectiveUntil',
        'latitudeDegrees',
        'longitudeDegrees',
        'depthKm',
        'elevationKm',
        'nominalSampleRateHz',
        'units',
        'orientationHorizontalDegrees',
        'orientationVerticalDegrees',
        'calibrationFactor',
        'calibrationPeriod',
        'calibrationEffectiveAt',
        'calibrationTimeShift',
        'calibrationStandardDeviation',
        'northDisplacementKm',
        'eastDisplacementKm',
        'verticalDisplacementKm',
        'description',
        'channelDataType',
        'channelBandType',
        'channelInstrumentType',
        'channelOrientationCode',
        'channelOrientationType',
        'calibrationResponseId',
        'fapResponseId'
      ],
      columnWidths: {
        name: 200,
        effectiveAt: 200,
        effectiveUntil: 200,
        latitudeDegrees: 105,
        longitudeDegrees: 105,
        depthKm: 105,
        elevationKm: 105,
        nominalSampleRateHz: 105,
        units: 105,
        orientationHorizontalDegrees: 155,
        orientationVerticalDegrees: 145,
        calibrationFactor: 200,
        calibrationPeriod: 200,
        calibrationEffectiveAt: 300,
        calibrationTimeShift: 200,
        calibrationStandardDeviation: 200,
        northDisplacementKm: 105,
        eastDisplacementKm: 105,
        verticalDisplacementKm: 105,
        description: 300,
        channelDataType: 200,
        channelBandType: 105,
        channelInstrumentType: 105,
        channelOrientationCode: 105,
        channelOrientationType: 200,
        calibrationResponseId: 200,
        fapResponseId: 200
      }
    }
  },
  [IanDisplays.MAGNITUDE]: {
    visibleMagnitudeTypes: {
      MB: true,
      MB_CODA: true,
      MB_MB: true,
      MB_MLE: true,
      MB_PG: true,
      MB_REL_T: true,
      ML: true,
      MS: true,
      MS_MLE: true,
      MS_VMAX: true,
      MW_CODA: true
    },
    displayOne: {
      columnVisibility: {
        restraint: true,
        preferred: true,
        magnitude__MB: true,
        stdDev__MB: true,
        defining__MB: true,
        nonDefining__MB: true,
        magnitude__MB_CODA: true,
        stdDev__MB_CODA: true,
        defining__MB_CODA: true,
        nonDefining__MB_CODA: true,
        magnitude__MB_MB: true,
        stdDev__MB_MB: true,
        defining__MB_MB: true,
        nonDefining__MB_MB: true,
        magnitude__MB_MLE: true,
        stdDev__MB_MLE: true,
        defining__MB_MLE: true,
        nonDefining__MB_MLE: true,
        detecting__MB_MLE: true,
        nonDetecting__MB_MLE: true,
        magnitude__MB_PG: true,
        stdDev__MB_PG: true,
        defining__MB_PG: true,
        nonDefining__MB_PG: true,
        magnitude__MB_REL_T: true,
        stdDev__MB_REL_T: true,
        defining__MB_REL_T: true,
        nonDefining__MB_REL_T: true,
        magnitude__ML: true,
        stdDev__ML: true,
        defining__ML: true,
        nonDefining__ML: true,
        magnitude__MS: true,
        stdDev__MS: true,
        defining__MS: true,
        nonDefining__MS: true,
        magnitude__MS_MLE: true,
        stdDev__MS_MLE: true,
        defining__MS_MLE: true,
        nonDefining__MS_MLE: true,
        detecting__MS_MLE: true,
        nonDetecting__MS_MLE: true,
        magnitude__MS_VMAX: true,
        stdDev__MS_VMAX: true,
        defining__MS_VMAX: true,
        nonDefining__MS_VMAX: true,
        magnitude__MW_CODA: true,
        stdDev__MW_CODA: true,
        defining__MW_CODA: true,
        nonDefining__MW_CODA: true
      },
      pinnedColumns: {},
      columnOrder: [
        'restraint',
        'preferred',
        'magnitude__MB',
        'stdDev__MB',
        'defining__MB',
        'nonDefining__MB',
        'magnitude__MB_CODA',
        'stdDev__MB_CODA',
        'defining__MB_CODA',
        'nonDefining__MB_CODA',
        'magnitude__MB_MB',
        'stdDev__MB_MB',
        'defining__MB_MB',
        'nonDefining__MB_MB',
        'magnitude__MB_MLE',
        'stdDev__MB_MLE',
        'defining__MB_MLE',
        'nonDefining__MB_MLE',
        'detecting__MB_MLE',
        'nonDetecting__MB_MLE',
        'magnitude__MB_PG',
        'stdDev__MB_PG',
        'defining__MB_PG',
        'nonDefining__MB_PG',
        'magnitude__MB_REL_T',
        'stdDev__MB_REL_T',
        'defining__MB_REL_T',
        'nonDefining__MB_REL_T',
        'magnitude__ML',
        'stdDev__ML',
        'defining__ML',
        'nonDefining__ML',
        'magnitude__MS',
        'stdDev__MS',
        'defining__MS',
        'nonDefining__MS',
        'magnitude__MS_MLE',
        'stdDev__MS_MLE',
        'defining__MS_MLE',
        'nonDefining__MS_MLE',
        'detecting__MS_MLE',
        'nonDetecting__MS_MLE',
        'magnitude__MS_VMAX',
        'stdDev__MS_VMAX',
        'defining__MS_VMAX',
        'nonDefining__MS_VMAX',
        'magnitude__MW_CODA',
        'stdDev__MW_CODA',
        'defining__MW_CODA',
        'nonDefining__MW_CODA'
      ],
      columnWidths: {
        restraint: 195,
        preferred: 105,
        magnitude__MB: 130,
        stdDev__MB: 130,
        defining__MB: 130,
        nonDefining__MB: 130,
        magnitude__MB_CODA: 130,
        stdDev__MB_CODA: 130,
        defining__MB_CODA: 130,
        nonDefining__MB_CODA: 130,
        magnitude__MB_MB: 130,
        stdDev__MB_MB: 130,
        defining__MB_MB: 130,
        nonDefining__MB_MB: 130,
        magnitude__MB_MLE: 130,
        stdDev__MB_MLE: 130,
        defining__MB_MLE: 130,
        nonDefining__MB_MLE: 130,
        detecting__MB_MLE: 130,
        nonDetecting__MB_MLE: 140,
        magnitude__MB_PG: 130,
        stdDev__MB_PG: 130,
        defining__MB_PG: 130,
        nonDefining__MB_PG: 130,
        magnitude__MB_REL_T: 130,
        stdDev__MB_REL_T: 130,
        defining__MB_REL_T: 130,
        nonDefining__MB_REL_T: 130,
        magnitude__ML: 130,
        stdDev__ML: 130,
        defining__ML: 130,
        nonDefining__ML: 130,
        magnitude__MS: 130,
        stdDev__MS: 130,
        defining__MS: 130,
        nonDefining__MS: 130,
        magnitude__MS_MLE: 130,
        stdDev__MS_MLE: 130,
        defining__MS_MLE: 130,
        nonDefining__MS_MLE: 130,
        detecting__MS_MLE: 130,
        nonDetecting__MS_MLE: 140,
        magnitude__MS_VMAX: 130,
        stdDev__MS_VMAX: 130,
        defining__MS_VMAX: 130,
        nonDefining__MS_VMAX: 130,
        magnitude__MW_CODA: 130,
        stdDev__MW_CODA: 130,
        defining__MW_CODA: 130,
        nonDefining__MW_CODA: 130
      }
    },
    displayTwo: {
      columnVisibility: {
        az: true,
        station: true,
        distance: true,
        'associatedSignalDetections.MB.conflict': true,
        'associatedSignalDetections.MB.isAddedSignalDetection': true,
        'associatedSignalDetections.MB.isDeletedSignalDetection': true,
        'associatedSignalDetections.MB.needsAmplitudeReview': true,
        channel__MB: true,
        phase__MB: true,
        amplitude__MB: true,
        period__MB: true,
        mag__MB: true,
        residual__MB: true,
        used__MB: true,
        defining__MB: true,
        'associatedSignalDetections.MB_CODA.conflict': true,
        'associatedSignalDetections.MB_CODA.isAddedSignalDetection': true,
        'associatedSignalDetections.MB_CODA.isDeletedSignalDetection': true,
        'associatedSignalDetections.MB_CODA.needsAmplitudeReview': true,
        channel__MB_CODA: true,
        phase__MB_CODA: true,
        amplitude__MB_CODA: true,
        period__MB_CODA: true,
        mag__MB_CODA: true,
        residual__MB_CODA: true,
        used__MB_CODA: true,
        defining__MB_CODA: true,
        'associatedSignalDetections.MB_MB.conflict': true,
        'associatedSignalDetections.MB_MB.isAddedSignalDetection': true,
        'associatedSignalDetections.MB_MB.isDeletedSignalDetection': true,
        'associatedSignalDetections.MB_MB.needsAmplitudeReview': true,
        channel__MB_MB: true,
        phase__MB_MB: true,
        amplitude__MB_MB: true,
        period__MB_MB: true,
        mag__MB_MB: true,
        residual__MB_MB: true,
        used__MB_MB: true,
        defining__MB_MB: true,
        'associatedSignalDetections.MB_MLE.conflict': true,
        'associatedSignalDetections.MB_MLE.isAddedSignalDetection': true,
        'associatedSignalDetections.MB_MLE.isDeletedSignalDetection': true,
        'associatedSignalDetections.MB_MLE.needsAmplitudeReview': true,
        channel__MB_MLE: true,
        phase__MB_MLE: true,
        amplitude__MB_MLE: true,
        period__MB_MLE: true,
        mag__MB_MLE: true,
        residual__MB_MLE: true,
        used__MB_MLE: true,
        defining__MB_MLE: true,
        'associatedSignalDetections.MB_PG.conflict': true,
        'associatedSignalDetections.MB_PG.isAddedSignalDetection': true,
        'associatedSignalDetections.MB_PG.isDeletedSignalDetection': true,
        'associatedSignalDetections.MB_PG.needsAmplitudeReview': true,
        channel__MB_PG: true,
        phase__MB_PG: true,
        amplitude__MB_PG: true,
        period__MB_PG: true,
        mag__MB_PG: true,
        residual__MB_PG: true,
        used__MB_PG: true,
        defining__MB_PG: true,
        'associatedSignalDetections.MB_REL_T.conflict': true,
        'associatedSignalDetections.MB_REL_T.isAddedSignalDetection': true,
        'associatedSignalDetections.MB_REL_T.isDeletedSignalDetection': true,
        'associatedSignalDetections.MB_REL_T.needsAmplitudeReview': true,
        channel__MB_REL_T: true,
        phase__MB_REL_T: true,
        amplitude__MB_REL_T: true,
        period__MB_REL_T: true,
        mag__MB_REL_T: true,
        residual__MB_REL_T: true,
        used__MB_REL_T: true,
        defining__MB_REL_T: true,
        'associatedSignalDetections.ML.conflict': true,
        'associatedSignalDetections.ML.isAddedSignalDetection': true,
        'associatedSignalDetections.ML.isDeletedSignalDetection': true,
        'associatedSignalDetections.ML.needsAmplitudeReview': true,
        channel__ML: true,
        phase__ML: true,
        amplitude__ML: true,
        period__ML: true,
        mag__ML: true,
        residual__ML: true,
        used__ML: true,
        defining__ML: true,
        'associatedSignalDetections.MS.conflict': true,
        'associatedSignalDetections.MS.isAddedSignalDetection': true,
        'associatedSignalDetections.MS.isDeletedSignalDetection': true,
        'associatedSignalDetections.MS.needsAmplitudeReview': true,
        channel__MS: true,
        phase__MS: true,
        amplitude__MS: true,
        period__MS: true,
        mag__MS: true,
        residual__MS: true,
        used__MS: true,
        defining__MS: true,
        'associatedSignalDetections.MS_MLE.conflict': true,
        'associatedSignalDetections.MS_MLE.isAddedSignalDetection': true,
        'associatedSignalDetections.MS_MLE.isDeletedSignalDetection': true,
        'associatedSignalDetections.MS_MLE.needsAmplitudeReview': true,
        channel__MS_MLE: true,
        phase__MS_MLE: true,
        amplitude__MS_MLE: true,
        period__MS_MLE: true,
        mag__MS_MLE: true,
        residual__MS_MLE: true,
        used__MS_MLE: true,
        defining__MS_MLE: true,
        'associatedSignalDetections.MS_VMAX.conflict': true,
        'associatedSignalDetections.MS_VMAX.isAddedSignalDetection': true,
        'associatedSignalDetections.MS_VMAX.isDeletedSignalDetection': true,
        'associatedSignalDetections.MS_VMAX.needsAmplitudeReview': true,
        channel__MS_VMAX: true,
        phase__MS_VMAX: true,
        amplitude__MS_VMAX: true,
        period__MS_VMAX: true,
        mag__MS_VMAX: true,
        residual__MS_VMAX: true,
        used__MS_VMAX: true,
        defining__MS_VMAX: true,
        'associatedSignalDetections.MW_CODA.conflict': true,
        'associatedSignalDetections.MW_CODA.isAddedSignalDetection': true,
        'associatedSignalDetections.MW_CODA.isDeletedSignalDetection': true,
        'associatedSignalDetections.MW_CODA.needsAmplitudeReview': true,
        channel__MW_CODA: true,
        phase__MW_CODA: true,
        amplitude__MW_CODA: true,
        period__MW_CODA: true,
        mag__MW_CODA: true,
        residual__MW_CODA: true,
        used__MW_CODA: true,
        defining__MW_CODA: true
      },
      pinnedColumns: {},
      columnOrder: [
        'az',
        'station',
        'distance',
        'associatedSignalDetections.MB.conflict',
        'associatedSignalDetections.MB.isAddedSignalDetection',
        'associatedSignalDetections.MB.isDeletedSignalDetection',
        'associatedSignalDetections.MB.needsAmplitudeReview',
        'channel__MB',
        'phase__MB',
        'amplitude__MB',
        'period__MB',
        'mag__MB',
        'residual__MB',
        'used__MB',
        'defining__MB',
        'associatedSignalDetections.MB_CODA.conflict',
        'associatedSignalDetections.MB_CODA.isAddedSignalDetection',
        'associatedSignalDetections.MB_CODA.isDeletedSignalDetection',
        'associatedSignalDetections.MB_CODA.needsAmplitudeReview',
        'channel__MB_CODA',
        'phase__MB_CODA',
        'amplitude__MB_CODA',
        'period__MB_CODA',
        'mag__MB_CODA',
        'residual__MB_CODA',
        'used__MB_CODA',
        'defining__MB_CODA',
        'associatedSignalDetections.MB_MB.conflict',
        'associatedSignalDetections.MB_MB.isAddedSignalDetection',
        'associatedSignalDetections.MB_MB.isDeletedSignalDetection',
        'associatedSignalDetections.MB_MB.needsAmplitudeReview',
        'channel__MB_MB',
        'phase__MB_MB',
        'amplitude__MB_MB',
        'period__MB_MB',
        'mag__MB_MB',
        'residual__MB_MB',
        'used__MB_MB',
        'defining__MB_MB',
        'associatedSignalDetections.MB_MLE.conflict',
        'associatedSignalDetections.MB_MLE.isAddedSignalDetection',
        'associatedSignalDetections.MB_MLE.isDeletedSignalDetection',
        'associatedSignalDetections.MB_MLE.needsAmplitudeReview',
        'channel__MB_MLE',
        'phase__MB_MLE',
        'amplitude__MB_MLE',
        'period__MB_MLE',
        'mag__MB_MLE',
        'residual__MB_MLE',
        'used__MB_MLE',
        'defining__MB_MLE',
        'associatedSignalDetections.MB_PG.conflict',
        'associatedSignalDetections.MB_PG.isAddedSignalDetection',
        'associatedSignalDetections.MB_PG.isDeletedSignalDetection',
        'associatedSignalDetections.MB_PG.needsAmplitudeReview',
        'channel__MB_PG',
        'phase__MB_PG',
        'amplitude__MB_PG',
        'period__MB_PG',
        'mag__MB_PG',
        'residual__MB_PG',
        'used__MB_PG',
        'defining__MB_PG',
        'associatedSignalDetections.MB_REL_T.conflict',
        'associatedSignalDetections.MB_REL_T.isAddedSignalDetection',
        'associatedSignalDetections.MB_REL_T.isDeletedSignalDetection',
        'associatedSignalDetections.MB_REL_T.needsAmplitudeReview',
        'channel__MB_REL_T',
        'phase__MB_REL_T',
        'amplitude__MB_REL_T',
        'period__MB_REL_T',
        'mag__MB_REL_T',
        'residual__MB_REL_T',
        'used__MB_REL_T',
        'defining__MB_REL_T',
        'associatedSignalDetections.ML.conflict',
        'associatedSignalDetections.ML.isAddedSignalDetection',
        'associatedSignalDetections.ML.isDeletedSignalDetection',
        'associatedSignalDetections.ML.needsAmplitudeReview',
        'channel__ML',
        'phase__ML',
        'amplitude__ML',
        'period__ML',
        'mag__ML',
        'residual__ML',
        'used__ML',
        'defining__ML',
        'associatedSignalDetections.MS.conflict',
        'associatedSignalDetections.MS.isAddedSignalDetection',
        'associatedSignalDetections.MS.isDeletedSignalDetection',
        'associatedSignalDetections.MS.needsAmplitudeReview',
        'channel__MS',
        'phase__MS',
        'amplitude__MS',
        'period__MS',
        'mag__MS',
        'residual__MS',
        'used__MS',
        'defining__MS',
        'associatedSignalDetections.MS_MLE.conflict',
        'associatedSignalDetections.MS_MLE.isAddedSignalDetection',
        'associatedSignalDetections.MS_MLE.isDeletedSignalDetection',
        'associatedSignalDetections.MS_MLE.needsAmplitudeReview',
        'channel__MS_MLE',
        'phase__MS_MLE',
        'amplitude__MS_MLE',
        'period__MS_MLE',
        'mag__MS_MLE',
        'residual__MS_MLE',
        'used__MS_MLE',
        'defining__MS_MLE',
        'associatedSignalDetections.MS_VMAX.conflict',
        'associatedSignalDetections.MS_VMAX.isAddedSignalDetection',
        'associatedSignalDetections.MS_VMAX.isDeletedSignalDetection',
        'associatedSignalDetections.MS_VMAX.needsAmplitudeReview',
        'channel__MS_VMAX',
        'phase__MS_VMAX',
        'amplitude__MS_VMAX',
        'period__MS_VMAX',
        'mag__MS_VMAX',
        'residual__MS_VMAX',
        'used__MS_VMAX',
        'defining__MS_VMAX',
        'associatedSignalDetections.MW_CODA.conflict',
        'associatedSignalDetections.MW_CODA.isAddedSignalDetection',
        'associatedSignalDetections.MW_CODA.isDeletedSignalDetection',
        'associatedSignalDetections.MW_CODA.needsAmplitudeReview',
        'channel__MW_CODA',
        'phase__MW_CODA',
        'amplitude__MW_CODA',
        'period__MW_CODA',
        'mag__MW_CODA',
        'residual__MW_CODA',
        'used__MW_CODA',
        'defining__MW_CODA'
      ],
      columnWidths: {
        az: 100,
        station: 100,
        distance: 100,
        'associatedSignalDetections.MB.conflict': 65,
        'associatedSignalDetections.MB.isAddedSignalDetection': 65,
        'associatedSignalDetections.MB.isDeletedSignalDetection': 65,
        'associatedSignalDetections.MB.needsAmplitudeReview': 65,
        channel__MB: 100,
        phase__MB: 100,
        amplitude__MB: 100,
        period__MB: 100,
        mag__MB: 100,
        residual__MB: 100,
        used__MB: 65,
        defining__MB: 62,
        'associatedSignalDetections.MB_CODA.conflict': 65,
        'associatedSignalDetections.MB_CODA.isAddedSignalDetection': 65,
        'associatedSignalDetections.MB_CODA.isDeletedSignalDetection': 65,
        'associatedSignalDetections.MB_CODA.needsAmplitudeReview': 65,
        channel__MB_CODA: 100,
        phase__MB_CODA: 100,
        amplitude__MB_CODA: 100,
        period__MB_CODA: 100,
        mag__MB_CODA: 100,
        residual__MB_CODA: 100,
        used__MB_CODA: 65,
        defining__MB_CODA: 62,
        'associatedSignalDetections.MB_MB.conflict': 65,
        'associatedSignalDetections.MB_MB.isAddedSignalDetection': 65,
        'associatedSignalDetections.MB_MB.isDeletedSignalDetection': 65,
        'associatedSignalDetections.MB_MB.needsAmplitudeReview': 65,
        channel__MB_MB: 100,
        phase__MB_MB: 100,
        amplitude__MB_MB: 100,
        period__MB_MB: 100,
        mag__MB_MB: 100,
        residual__MB_MB: 100,
        used__MB_MB: 65,
        defining__MB_MB: 62,
        'associatedSignalDetections.MB_MLE.conflict': 65,
        'associatedSignalDetections.MB_MLE.isAddedSignalDetection': 65,
        'associatedSignalDetections.MB_MLE.isDeletedSignalDetection': 65,
        'associatedSignalDetections.MB_MLE.needsAmplitudeReview': 65,
        channel__MB_MLE: 100,
        phase__MB_MLE: 100,
        amplitude__MB_MLE: 100,
        period__MB_MLE: 100,
        mag__MB_MLE: 100,
        residual__MB_MLE: 100,
        used__MB_MLE: 65,
        defining__MB_MLE: 62,
        'associatedSignalDetections.MB_PG.conflict': 65,
        'associatedSignalDetections.MB_PG.isAddedSignalDetection': 65,
        'associatedSignalDetections.MB_PG.isDeletedSignalDetection': 65,
        'associatedSignalDetections.MB_PG.needsAmplitudeReview': 65,
        channel__MB_PG: 100,
        phase__MB_PG: 100,
        amplitude__MB_PG: 100,
        period__MB_PG: 100,
        mag__MB_PG: 100,
        residual__MB_PG: 100,
        used__MB_PG: 65,
        defining__MB_PG: 62,
        'associatedSignalDetections.MB_REL_T.conflict': 65,
        'associatedSignalDetections.MB_REL_T.isAddedSignalDetection': 65,
        'associatedSignalDetections.MB_REL_T.isDeletedSignalDetection': 65,
        'associatedSignalDetections.MB_REL_T.needsAmplitudeReview': 65,
        channel__MB_REL_T: 100,
        phase__MB_REL_T: 100,
        amplitude__MB_REL_T: 100,
        period__MB_REL_T: 100,
        mag__MB_REL_T: 100,
        residual__MB_REL_T: 100,
        used__MB_REL_T: 65,
        defining__MB_REL_T: 62,
        'associatedSignalDetections.ML.conflict': 65,
        'associatedSignalDetections.ML.isAddedSignalDetection': 65,
        'associatedSignalDetections.ML.isDeletedSignalDetection': 65,
        'associatedSignalDetections.ML.needsAmplitudeReview': 65,
        channel__ML: 100,
        phase__ML: 100,
        amplitude__ML: 100,
        period__ML: 100,
        mag__ML: 100,
        residual__ML: 100,
        used__ML: 65,
        defining__ML: 62,
        'associatedSignalDetections.MS.conflict': 65,
        'associatedSignalDetections.MS.isAddedSignalDetection': 65,
        'associatedSignalDetections.MS.isDeletedSignalDetection': 65,
        'associatedSignalDetections.MS.needsAmplitudeReview': 65,
        channel__MS: 100,
        phase__MS: 100,
        amplitude__MS: 100,
        period__MS: 100,
        mag__MS: 100,
        residual__MS: 100,
        used__MS: 65,
        defining__MS: 62,
        'associatedSignalDetections.MS_MLE.conflict': 65,
        'associatedSignalDetections.MS_MLE.isAddedSignalDetection': 65,
        'associatedSignalDetections.MS_MLE.isDeletedSignalDetection': 65,
        'associatedSignalDetections.MS_MLE.needsAmplitudeReview': 65,
        channel__MS_MLE: 100,
        phase__MS_MLE: 100,
        amplitude__MS_MLE: 100,
        period__MS_MLE: 100,
        mag__MS_MLE: 100,
        residual__MS_MLE: 100,
        used__MS_MLE: 65,
        defining__MS_MLE: 62,
        'associatedSignalDetections.MS_VMAX.conflict': 65,
        'associatedSignalDetections.MS_VMAX.isAddedSignalDetection': 65,
        'associatedSignalDetections.MS_VMAX.isDeletedSignalDetection': 65,
        'associatedSignalDetections.MS_VMAX.needsAmplitudeReview': 65,
        channel__MS_VMAX: 100,
        phase__MS_VMAX: 100,
        amplitude__MS_VMAX: 100,
        period__MS_VMAX: 100,
        mag__MS_VMAX: 100,
        residual__MS_VMAX: 100,
        used__MS_VMAX: 65,
        defining__MS_VMAX: 62,
        'associatedSignalDetections.MW_CODA.conflict': 65,
        'associatedSignalDetections.MW_CODA.isAddedSignalDetection': 65,
        'associatedSignalDetections.MW_CODA.isDeletedSignalDetection': 65,
        'associatedSignalDetections.MW_CODA.needsAmplitudeReview': 65,
        channel__MW_CODA: 100,
        phase__MW_CODA: 100,
        amplitude__MW_CODA: 100,
        period__MW_CODA: 100,
        mag__MW_CODA: 100,
        residual__MW_CODA: 100,
        used__MW_CODA: 65,
        defining__MW_CODA: 62
      }
    }
  }
};

export const waveformDisplayLayoutData: WaveformDisplayLayout = {
  visibleSignalDetections: {
    signalDetectionBeforeInterval: true,
    signalDetectionAfterInterval: true,
    signalDetectionAssociatedToOpenEvent: true,
    signalDetectionAssociatedToCompletedEvent: true,
    signalDetectionAssociatedToOtherEvent: true,
    signalDetectionConflicts: true,
    signalDetectionDeleted: true,
    signalDetectionUnassociated: true
  }
};

const stationVisibilityListData: StationVisibilityList = {
  name: 'Default Station Visibility',
  stations: [convertToEntityReference(asar, 'name'), convertToEntityReference(pdar, 'name')]
};

/**
 * Testing data for {@link UserPreferencesKeyboardShortcuts}
 */
const userPreferencesKeyboardShortcutsData: UserPreferencesKeyboardShortcuts = {
  clickEvents: {},
  middleClickEvents: {},
  rightClickEvents: {},
  doubleClickEvents: {},
  dragEvents: {},
  scrollEvents: {},
  hotkeys: {}
};

/**
 * Testing data for {@link UiUserPreferences}
 */
export const uiUserPreferencesData: UiUserPreferences = {
  defaultWorkspaceLayout: 'Analyst Displays Layout',
  globalPreferences: globalPreferencesData,
  workspaceLayouts: workspaceLayoutsData,
  customFilterList: undefined,
  mapDisplaySettings: mapDisplaySettingsData,
  displayLayouts: displayLayoutsData,
  waveformDisplayLayout: waveformDisplayLayoutData,
  stationVisibilityLists: [stationVisibilityListData],
  keyboardShortcuts: userPreferencesKeyboardShortcutsData
};

export const currentUserProfileData: UserProfile = {
  userId: 'testUser',
  userPreferences: uiUserPreferencesData
};

export const defaultUserProfileData: UserProfile = {
  userId: 'defaultUser',
  userPreferences: uiUserPreferencesData
};
